### ISSUE TITLE
error

### ISSUE THREAD

**Issue by colourfulhacker** [webdeveloperkanai/wordpress-certificate-verifyer-pro#1]
Fatal error: Cannot redeclare course_certificate_plugin_styles_scripts() (previously declared in /home/cehpointco/public_html/elearning/wp-content/plugins/certificate-verification/course-certificate-verification.php:22) in /home/cehpointco/public_html/elearning/wp-content/plugins/My certificate-verification/course-certificate-verification.php on line 24

**Comment by webdeveloperkanai** [comment]
Kindly remove the old version of the plugin. Use updated version always. Thanks
